### ISSUE TITLE
it not work on macos

### ISSUE THREAD

**Issue by powersee** [bunglegrind/save-as-ebook#13] opened 2023-03-28 13:03 UTC
The code works on my Windows 11 Edge browser, but it doesn't seem to work on my Mac with Edge. When I click on "save page," I can see the "busy" icon, and the console shows the message 

```
Prepare Content...
saveEbook.js:194 zipped !
saveEbook.js:195 Using pipenv and Docker | Simon Willison’s TILs.epub
```

But nothing download..

The link i use to test 
https://til.simonwillison.net/docker/pipenv-and-docker

**Comment by bunglegrind** [comment] 2023-04-14 10:49
Sorry, I haven't received any notification of this issue. However, I didn't expect anybody would create an issue...

First of all, at the moment this is supposed to be a personal project, which I've created because of the bugs of the original save-as-ebook and its limitations. Of course, you can use it, but don't expect that I'm going to work on issues that are beyond my personal scope. 

Having said that, which branch are you using? I suggest you the master branch, which is mostly a bug fixing branch of the original extension. 
I'm using Firefox on Windows, I don't have any Mac to test it. Anyway, could you try again with extension console opened? type edge://inspect, click on extension, and then on inspect.  I suppose it's related to the background script.

**Comment by powersee** [comment] 2023-04-14 11:40
Thanks your reply. I really like what you did in this extension.

Use it i can see which html tag will be remove, i want to remove the footer and header in body, because i just want to save the body content.

With this project i can see the change, it help me a lot, thank you again.

Yes, i understand, i just want to find out the problem. If you can help me, I would appreciate it. If you don't have the time, or if you don't know the problem. That doesn't matter, either.

I am using the master branch, here is the git log

```
commit 90fb062d3ff16b56f9eac9b5a82c7f366164c99b (HEAD -> master, origin/master, origin/HEAD)
Author: bunglegrind <bunglegrind@xxxx>
Date:   Mon Aug 15 08:57:25 2022 +0200

    insert web-ext local dependency, add eol=lf for css files, fix issue #11
```



the error from inspect console

```
Error in event handler: TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at _execRequest (chrome-extension://nobikekhfpkonjojhmipioppjpglebfd/background.js:452:24)
_generated_background_page.html:1 
        
       Unchecked runtime.lastError: The message port closed before a response was received.
_generated_background_page.html:1 
        
       Unchecked runtime.lastError: The message port closed before a response was received.
_generated_background_page.html:1 
        
       Error in event handler: TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at _execRequest (chrome-extension://nobikekhfpkonjojhmipioppjpglebfd/background.js:452:24)
_generated_background_page.html:1 
        
       Unchecked runtime.lastError: The message port closed before a response was received.
```

<img width="1070" alt="powersee-2023-04-14 19 39 07" src="https://user-images.githubusercontent.com/38074760/232034051-06c02720-9df7-431f-b2f7-3198e38396bc.png">


```
Unchecked runtime.lastError: The message port closed before a response was received.
_generated_background_page.html:1 
        
       Error in event handler: TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at _execRequest (chrome-extension://nobikekhfpkonjojhmipioppjpglebfd/background.js:452:24)
```

the log from browser console
```
CORS not enabled or empty iframe. Discarding save-as-ebook-iframe-0
extractHtml.js:202 save-as-ebook-iframe-1
saveEbook.js:47 Prepare Content...
saveEbook.js:211 zipped !
```

Test with this link http://antirez.com/news/135

**Comment by powersee** [comment] 2023-04-14 14:49
No, the original extension work well.
And your extension can work on windows11 edge browser, but not work on mac edge.
I am using Mac mini M1.

**Comment by bunglegrind** [comment] 2023-04-14 17:01
Ok...let me guess. The culprit is jszip. I'm using a different version (3.9.1) of the one used by the original extension (I suppose it's version 3.0.0). 
Try to replace in the libs folder jszip.min.js with this one:

https://github.com/Stuk/jszip/blob/v3.0.0/dist/jszip.min.js

and let me know if you still have the error.

**Comment by bunglegrind** [comment] 2023-04-14 17:11
I've deleted the previous comment....I was wrong....maybe. One of the libs I removed was filesaver.js, which can manage some edge-cases concerning macos. 

https://github.com/eligrey/FileSaver.js/

During the weekend if I have enough free time I will try to create a branch including again the utility.

**Comment by powersee** [comment] 2023-04-14 17:37
Wow, finally, thank you very much! 👍

**Comment by bunglegrind** [comment] 2023-04-14 18:24
here it is, quick and dirty:

https://github.com/bunglegrind/save-as-ebook/tree/macos-support

**Comment by bunglegrind** [comment] 2023-04-14 22:07
> which can manage some edge-cases concerning macos
Uh not really. I remember: I moved the download to the background because I didn't like the approach filesaver uses.

Let me if it works, I would like to test some other solutions too, if you have time

**Comment by powersee** [comment] 2023-04-15 00:24
nice, it work now. Thanks again.

**Comment by bunglegrind** [comment] 2023-04-15 06:14
Sorry, but it stays open until I patch master

**Comment by bunglegrind** [comment] 2023-04-15 07:14
> I am using Mac mini M1.
 OS version and Edge version, please?

And then I kindly ask you to try again with the master branch. Now I write more when an error occurs, and I've added a callback in the content script message sender (maybe it's related to content script closing

**Comment by powersee** [comment] 2023-04-15 07:22
my macos version 13.3 Ventura
Edge version 94.0.992.38

I try the master branch just now. It can't download the epub.

log in console (browser)
```
CORS not enabled or empty iframe. Discarding save-as-ebook-iframe-0
extractHtml.js:202 save-as-ebook-iframe-1
saveEbook.js:47 Prepare Content...
saveEbook.js:194 zipped !
saveEbook.js:195 Programming and Writing - <antirez>.epub
saveEbook.js:201 eBook is not a Blob. Aborting
```

**Comment by powersee** [comment] 2023-04-15 07:45
update Edge to 112.0.1722.48

click save page show the same info in browser console, nothing in page console.

I try the export css style. It work, but i get this error in page console.
```
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

**Comment by bunglegrind** [comment] 2023-04-15 09:24
oh crud, it looks like I was right in the comment I deleted...try again another time, I've added some more logs, expecially concerning jszip.
What do you mean for "browser console"? The console you see when you click inspect on the extension page?

The error you see when download the styles is okay, I will get rid of it when the next branch will be completed.

**Comment by powersee** [comment] 2023-04-15 10:14
I try the latest code.

the log is same.

> What do you mean for "browser console"?

i mean this, or what should i call it?
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/38074760/232207684-01eb5606-dfe0-4591-a1f6-be1f305df5b7.png">

extension console

<img width="773" alt="powersee-2023-04-15 18 12 43" src="https://user-images.githubusercontent.com/38074760/232207752-74e70717-933e-4633-8b32-848dd4e4bece.png">

**Comment by bunglegrind** [comment] 2023-04-15 11:38
thanks for your effort. 
The culprit is chrome.runtime.sendMessage which currupts (converts? No idea) in some way the blob instance. I will try some workaround, but for the moment, if you have time, could you please try the extension on chrome on macos?

**Comment by powersee** [comment] 2023-04-15 13:33
you are welcome.

I will do what i can. And i just download chrome in Mac. Try the extension, it's same as Edge browser.

**Comment by powersee** [comment] 2023-04-15 13:46
Can I ask you some questions? Can this extension set it to save only the body content? I use it often to save articles from various blogs. I need to set my own css e. g

```
footer, body header, .comment {
    display: none;
}
```

I think you're quite familiar with this extension. Do you know where the modifications can do this more quickly? For example, tell me about where the code is about this? I'll go and see.

**Comment by bunglegrind** [comment] 2023-04-15 13:58
ok, it's a chromium bug. I couldn' find anything on their issue tracker, though. Since I cannot reproduce the bug in my environment, I cannot open an issue...well, if I can somehow get my hands on a mac (and have enough free time) I will try to inform chromium team.

Anyway, I've just pushed (on the master branch) a semi-definitive fix

**Comment by bunglegrind** [comment] 2023-04-15 15:57
oh...and if you want, I've just uploaded a minimal extension in order to reproduce the bug 

https://github.com/bunglegrind/bug-chromium

when the extension is enabled, a very large button will appear at the top of the tab you're visiting. Click it, and you'll have two alert windows, first one it's just to inform you that the test is starting, the second one gives the result of the test

**Comment by powersee** [comment] 2023-04-15 16:16
i try serveral times, but console show nothing.

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/38074760/232237362-becf7759-e18f-4215-a580-64c01f57a442.png">

**Comment by bunglegrind** [comment] 2023-04-15 16:24
No, it's okay. The error is written on the alert box in this case. I can send the results to the chromium team.

**Comment by bunglegrind** [comment] 2023-04-15 16:24
btw, if you test the latest master commit I can finalize the patch and close the issue :P

**Comment by bunglegrind** [comment] 2023-04-15 21:27
OK...it's a chromium bug in all the platforms, including windows. I found the issue on their bug tracker, is 10 years old...

https://bugs.chromium.org/p/chromium/issues/detail?id=248548

Firefox isn' affected:

https://discourse.mozilla.org/t/sending-blob-through-runtime-sendmessage-is-working-but-why/32030/4

The "fix" consists in sending the zip in a format which can be serialize in JSON. I think a typedArray should work. 

Are you really sure that the extension is working on chrome/edge in windows? It shouldn't...

Anywa, I'll patch it ASAP

**Comment by powersee** [comment] 2023-04-16 02:09
bug-chromium show the same as mac

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/38074760/232262242-d5b0030f-24b7-4e18-a603-ff906071d101.png">

but i use the master branch you

Commits on Aug 15, 2022 

it work well,  i already use it one month

**Comment by bunglegrind** [comment] 2023-04-16 11:12
Ok I should have it fixed on the master branch. Let me know if there are still problems.

**Closed by bunglegrind** 2023-04-16 11:12 UTC
Labels: bug
